# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timo/fun/cubing/min2phaseCXX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timo/fun/cubing/min2phaseCXX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timo/fun/cubing/min2phaseCXX/CMakeFiles /home/timo/fun/cubing/min2phaseCXX//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timo/fun/cubing/min2phaseCXX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named min2phase

# Build rule for target.
min2phase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 min2phase
.PHONY : min2phase

# fast build rule for target.
min2phase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/build
.PHONY : min2phase/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named server-example

# Build rule for target.
server-example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server-example
.PHONY : server-example

# fast build rule for target.
server-example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server-example.dir/build.make CMakeFiles/server-example.dir/build
.PHONY : server-example/fast

examples/benchmark.o: examples/benchmark.cpp.o
.PHONY : examples/benchmark.o

# target to build an object file
examples/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/examples/benchmark.cpp.o
.PHONY : examples/benchmark.cpp.o

examples/benchmark.i: examples/benchmark.cpp.i
.PHONY : examples/benchmark.i

# target to preprocess a source file
examples/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/examples/benchmark.cpp.i
.PHONY : examples/benchmark.cpp.i

examples/benchmark.s: examples/benchmark.cpp.s
.PHONY : examples/benchmark.s

# target to generate assembly for a file
examples/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/examples/benchmark.cpp.s
.PHONY : examples/benchmark.cpp.s

examples/example.o: examples/example.cpp.o
.PHONY : examples/example.o

# target to build an object file
examples/example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/examples/example.cpp.o
.PHONY : examples/example.cpp.o

examples/example.i: examples/example.cpp.i
.PHONY : examples/example.i

# target to preprocess a source file
examples/example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/examples/example.cpp.i
.PHONY : examples/example.cpp.i

examples/example.s: examples/example.cpp.s
.PHONY : examples/example.s

# target to generate assembly for a file
examples/example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/examples/example.cpp.s
.PHONY : examples/example.cpp.s

examples/server-example.o: examples/server-example.cpp.o
.PHONY : examples/server-example.o

# target to build an object file
examples/server-example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server-example.dir/build.make CMakeFiles/server-example.dir/examples/server-example.cpp.o
.PHONY : examples/server-example.cpp.o

examples/server-example.i: examples/server-example.cpp.i
.PHONY : examples/server-example.i

# target to preprocess a source file
examples/server-example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server-example.dir/build.make CMakeFiles/server-example.dir/examples/server-example.cpp.i
.PHONY : examples/server-example.cpp.i

examples/server-example.s: examples/server-example.cpp.s
.PHONY : examples/server-example.s

# target to generate assembly for a file
examples/server-example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server-example.dir/build.make CMakeFiles/server-example.dir/examples/server-example.cpp.s
.PHONY : examples/server-example.cpp.s

examples/tests.o: examples/tests.cpp.o
.PHONY : examples/tests.o

# target to build an object file
examples/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/examples/tests.cpp.o
.PHONY : examples/tests.cpp.o

examples/tests.i: examples/tests.cpp.i
.PHONY : examples/tests.i

# target to preprocess a source file
examples/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/examples/tests.cpp.i
.PHONY : examples/tests.cpp.i

examples/tests.s: examples/tests.cpp.s
.PHONY : examples/tests.s

# target to generate assembly for a file
examples/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/examples/tests.cpp.s
.PHONY : examples/tests.cpp.s

src/CubieCube.o: src/CubieCube.cpp.o
.PHONY : src/CubieCube.o

# target to build an object file
src/CubieCube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/CubieCube.cpp.o
.PHONY : src/CubieCube.cpp.o

src/CubieCube.i: src/CubieCube.cpp.i
.PHONY : src/CubieCube.i

# target to preprocess a source file
src/CubieCube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/CubieCube.cpp.i
.PHONY : src/CubieCube.cpp.i

src/CubieCube.s: src/CubieCube.cpp.s
.PHONY : src/CubieCube.s

# target to generate assembly for a file
src/CubieCube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/CubieCube.cpp.s
.PHONY : src/CubieCube.cpp.s

src/Search.o: src/Search.cpp.o
.PHONY : src/Search.o

# target to build an object file
src/Search.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/Search.cpp.o
.PHONY : src/Search.cpp.o

src/Search.i: src/Search.cpp.i
.PHONY : src/Search.i

# target to preprocess a source file
src/Search.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/Search.cpp.i
.PHONY : src/Search.cpp.i

src/Search.s: src/Search.cpp.s
.PHONY : src/Search.s

# target to generate assembly for a file
src/Search.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/Search.cpp.s
.PHONY : src/Search.cpp.s

src/coords.o: src/coords.cpp.o
.PHONY : src/coords.o

# target to build an object file
src/coords.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/coords.cpp.o
.PHONY : src/coords.cpp.o

src/coords.i: src/coords.cpp.i
.PHONY : src/coords.i

# target to preprocess a source file
src/coords.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/coords.cpp.i
.PHONY : src/coords.cpp.i

src/coords.s: src/coords.cpp.s
.PHONY : src/coords.s

# target to generate assembly for a file
src/coords.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/coords.cpp.s
.PHONY : src/coords.cpp.s

src/http.o: src/http.cpp.o
.PHONY : src/http.o

# target to build an object file
src/http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/http.cpp.o
.PHONY : src/http.cpp.o

src/http.i: src/http.cpp.i
.PHONY : src/http.i

# target to preprocess a source file
src/http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/http.cpp.i
.PHONY : src/http.cpp.i

src/http.s: src/http.cpp.s
.PHONY : src/http.s

# target to generate assembly for a file
src/http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/http.cpp.s
.PHONY : src/http.cpp.s

src/info.o: src/info.cpp.o
.PHONY : src/info.o

# target to build an object file
src/info.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/info.cpp.o
.PHONY : src/info.cpp.o

src/info.i: src/info.cpp.i
.PHONY : src/info.i

# target to preprocess a source file
src/info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/info.cpp.i
.PHONY : src/info.cpp.i

src/info.s: src/info.cpp.s
.PHONY : src/info.s

# target to generate assembly for a file
src/info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/info.cpp.s
.PHONY : src/info.cpp.s

src/min2phase.o: src/min2phase.cpp.o
.PHONY : src/min2phase.o

# target to build an object file
src/min2phase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/min2phase.cpp.o
.PHONY : src/min2phase.cpp.o

src/min2phase.i: src/min2phase.cpp.i
.PHONY : src/min2phase.i

# target to preprocess a source file
src/min2phase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/min2phase.cpp.i
.PHONY : src/min2phase.cpp.i

src/min2phase.s: src/min2phase.cpp.s
.PHONY : src/min2phase.s

# target to generate assembly for a file
src/min2phase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/min2phase.cpp.s
.PHONY : src/min2phase.cpp.s

src/tests.o: src/tests.cpp.o
.PHONY : src/tests.o

# target to build an object file
src/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/tests.cpp.o
.PHONY : src/tests.cpp.o

src/tests.i: src/tests.cpp.i
.PHONY : src/tests.i

# target to preprocess a source file
src/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/tests.cpp.i
.PHONY : src/tests.cpp.i

src/tests.s: src/tests.cpp.s
.PHONY : src/tests.s

# target to generate assembly for a file
src/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/tests.cpp.s
.PHONY : src/tests.cpp.s

src/tools.o: src/tools.cpp.o
.PHONY : src/tools.o

# target to build an object file
src/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/tools.cpp.o
.PHONY : src/tools.cpp.o

src/tools.i: src/tools.cpp.i
.PHONY : src/tools.i

# target to preprocess a source file
src/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/tools.cpp.i
.PHONY : src/tools.cpp.i

src/tools.s: src/tools.cpp.s
.PHONY : src/tools.s

# target to generate assembly for a file
src/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min2phase.dir/build.make CMakeFiles/min2phase.dir/src/tools.cpp.s
.PHONY : src/tools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... benchmark"
	@echo "... example"
	@echo "... min2phase"
	@echo "... server-example"
	@echo "... tests"
	@echo "... examples/benchmark.o"
	@echo "... examples/benchmark.i"
	@echo "... examples/benchmark.s"
	@echo "... examples/example.o"
	@echo "... examples/example.i"
	@echo "... examples/example.s"
	@echo "... examples/server-example.o"
	@echo "... examples/server-example.i"
	@echo "... examples/server-example.s"
	@echo "... examples/tests.o"
	@echo "... examples/tests.i"
	@echo "... examples/tests.s"
	@echo "... src/CubieCube.o"
	@echo "... src/CubieCube.i"
	@echo "... src/CubieCube.s"
	@echo "... src/Search.o"
	@echo "... src/Search.i"
	@echo "... src/Search.s"
	@echo "... src/coords.o"
	@echo "... src/coords.i"
	@echo "... src/coords.s"
	@echo "... src/http.o"
	@echo "... src/http.i"
	@echo "... src/http.s"
	@echo "... src/info.o"
	@echo "... src/info.i"
	@echo "... src/info.s"
	@echo "... src/min2phase.o"
	@echo "... src/min2phase.i"
	@echo "... src/min2phase.s"
	@echo "... src/tests.o"
	@echo "... src/tests.i"
	@echo "... src/tests.s"
	@echo "... src/tools.o"
	@echo "... src/tools.i"
	@echo "... src/tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

